name: example-environment
channels:
  - conda-forge
dependencies:
  - cython==3.0.12
  - numpy
  - setuptools
  - matplotlib
  - pip
  - pip:
    - datetime
    - calcephpy
    - ipywidgets
    - convertdate
