name: example-environment
channels:
  - conda-forge
dependencies:
  - cython
  - numpy
  - setuptools
  - matplotlib
  - pip
  - pip:
    - datetime
    - calcephpy
    - ipywidgets
    - convertdate
